### PR TITLE
Reset search to searchname

### PR DESCRIPTION
**Pull request by RuijianLu**
the command is still "search".

### CODE REVIEW

**Comment by muller317** [comment]
Seems like check style violation caused the failed checks, may you look into that？Thank you

**Comment by engyuhan** [comment]
LGTM

**Review by engyuhan — COMMENTED** [review]
LGTM

**Comment by RuijianLu** [comment]
> Seems like check style violation caused the failed checks, may you look into that？Thank you

corrected, thx.

**Pull request merged**
